---
dbType: mysql
jdbcUrl: jdbc:mysql://mysql:3306/saga?useSSL=false
dbHost: mysql
dbPort: 3306
dbUser: root
dbPass: rootpassword
dbName: saga
dbHistoryTopicName: db.history.topic
sourceTableName: MESSAGE
maximumPoolSize: 10
kafka: kafka:9092
zookeeper: zookeeper:2181
