# Singleton service factory configuration/IoC injection
singletons:
# HandlerProvider implementation
- com.networknt.server.HandlerProvider:
  - com.networknt.tram.cdc.server.CdcServer
# StartupHookProvider implementations, there are one to many and they are called in the same sequence defined.
- com.networknt.server.StartupHookProvider:
  - com.networknt.tram.cdc.server.CdcServerStartupHookProvider
# ShutdownHookProvider implementations, there are one to many and they are called in the same sequence defined.
- com.networknt.server.ShutdownHookProvider:
  - com.networknt.tram.cdc.server.CdcServerShutdownHookProvider
# MiddlewareHandler implementations, the calling sequence is as defined in the request/response chain.
